# Generated by Django 5.0.6 on 2024-07-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_structure', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='deleted_by',
        ),
    ]
